name: flog_logger
description: "Flutter package for logging."
version: 0.0.1
homepage: https://github.com/DavidNovak1521/flog
repository: https://github.com/DavidNovak1521/flog
documentation: https://github.com/DavidNovak1521/flog

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
